### ISSUE TITLE
[Feature Request] Google cloud storage

### ISSUE THREAD

**Issue by annymosse** [Slynova-Org/flydrive#103]
Hey, I would love to have support for Google cloud storage. The Google team recently published a library https://www.npmjs.com/package/@google-cloud/storage and it would be great to have this integrated as an alternative to AWS S3.

**Comment by targos** [comment]
Support for GCS is already implemented in the [next](https://github.com/Slynova-Org/flydrive/tree/next) branch.

**Comment by annymosse** [comment]
hi @targos  thanks for your quick reply and its a great news ,when should we use it? is it ready to use with adonisJS framework ?

**Comment by targos** [comment]
It is not ready yet. We are still working on the API for [version 1.0](https://github.com/Slynova-Org/flydrive/issues/87)

**Comment by annymosse** [comment]
@targos is there any plan to integrate it with adonisJS after the release ?

**Comment by RomainLanz** [comment]
Should be simple to update the version in `@adonisjs/drive`.

**Comment by annymosse** [comment]
i'm too excited for this new version, have a good luck at your works.

**Comment by siddiquipro** [comment]
@RomainLanz  when is it planned to be updated in @adonisjs/drive.
