### ISSUE TITLE
[Feature request] Scaleway Object Storage S3 

### ISSUE THREAD

**Issue by dasmikko** [Slynova-Org/flydrive#118]
Would it possible to support scaleway's object storage, as they follow the S3 api?

Link: https://www.scaleway.com/en/object-storage/

**Comment by dasmikko** [comment]
Nevermind, found out i can use the spaces driver

**Comment by RomainLanz** [comment]
Hey @dasmikko! 👋 

This is nice to know, if it works well could you please send a PR to update the readme and add a disk example?

**Comment by dasmikko** [comment]
Hey @RomainLanz !

I made a PR to update the readme

I'm unsure where and how you want the example
