### ISSUE TITLE
[Feature request] export exceptions via main entry point

### ISSUE THREAD

**Issue by jrbarnard** [Slynova-Org/flydrive#129]
Currently you can access internal exceptions via: 
```
import * as Exceptions from '@slynova/flydrive/build/Exceptions';
```

However it feels like these should be available at the top level, e.g:
```
import { Exceptions } from '@slynova/flydrive';
```

What do you think? I am happy to do a PR for this if there is interest

**Comment by RomainLanz** [comment]
Hey @jrbarnard! 👋 

This will be fixed in the next released!
