### ISSUE TITLE
Latest version doesn't work.

### ISSUE THREAD

**Issue by ojhaujjwal** [Slynova-Org/flydrive#144]
There is a dir called `Exceptions`:
<img width="421" alt="image" src="https://user-images.githubusercontent.com/4995501/84588654-1e27ec80-ae49-11ea-9afd-66024900b11c.png">

but on index.ts, `exceptions` is imported.
<img width="506" alt="image" src="https://user-images.githubusercontent.com/4995501/84588665-3c8de800-ae49-11ea-9f4c-71ea6e98a59d.png">

Can we have a better CI/CD pipeline? Everytime I have tried to use this library, there are always some very minor issues which may have been detected with a better CI pipeline.

**Comment by rijkvanzanten** [comment]
I just made a clean fork and built the package and am not seeing the `Exceptions` uppercased on my end.. Do you have any way to accurately reproduce this @ojhaujjwal?

![CleanShot 2020-06-29 at 10 53 53](https://user-images.githubusercontent.com/9141017/86021356-029b1500-b9f7-11ea-86e2-8b2664efae50.png)

Also the version I just installed through NPM doesn't seem to have the exceptions uppercased like you mentioned:

![CleanShot 2020-06-29 at 10 55 27](https://user-images.githubusercontent.com/9141017/86021465-1a729900-b9f7-11ea-9d9f-c188509cc69a.png)

---

I noticed this export was changed in https://github.com/Slynova-Org/flydrive/commit/16ecffc6ae63dc17914d3357ba78ed568e712e74. @targos do you know if the folder name was changed as well in the last release?

**Comment by stephenwf** [comment]
Removing the folder from NPM, Pinning to `1.0.2` and then installing worked for me. 

Exceptions folder is lower case in this release: https://unpkg.com/browse/@slynova/flydrive@1.0.2/build/ but broken in this one: https://unpkg.com/browse/@slynova/flydrive@1.0.1-alpha.0/build/
