### ISSUE TITLE
Type differences in Readable

### ISSUE THREAD

**Issue by rijkvanzanten** [Slynova-Org/flydrive#145]
Hi there!

I'm trying to combine [`busboy`](https://www.npmjs.com/package/busboy) with `flydrive`, however, when passing busboy's `file` (stream) to `flydrive`, I'm getting a TypeScript error stating that busboy's `NodeJS.ReadableStream` isn't compatible with flydrive's `Readable` type. I noticed `Readable` is imported from a fairly small front-end streaming library. Is there any reason why this type is chosen in particular? Would you accept a PR to change that out to be a NodeJS ReadableStream?

**Comment by rijkvanzanten** [comment]
For reference:

https://github.com/Slynova-Org/flydrive/blob/8e04e00b1e8433713acfbaac1beb8fbb37ddf9e5/packages/flydrive/src/LocalFileSystemStorage.ts#L183

https://github.com/DefinitelyTyped/DefinitelyTyped/blob/bf2a6e1785dc5f702846d56c092a092b7eb485b4/types/busboy/index.d.ts#L41

```
(parameter) fileStream: NodeJS.ReadableStream
Argument of type 'ReadableStream' is not assignable to parameter of type 'string | Readable | Buffer'.
  Type 'ReadableStream' is missing the following properties from type 'Readable': readableEncoding, readableEnded, readableHighWaterMark, readableLength, and 6 more.ts(2345)
```

**Comment by targos** [comment]
>  I noticed Readable is imported from a fairly small front-end streaming library.

What do you mean? We `import { Readable } from 'stream'`, which is provided by `@types/node`.

That said, I realized that [`Readable` is more specific than `NodeJS.ReadableStream`](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5ca1e873b7d45542b10b27b065a79a851ceb728a/types/node/stream.d.ts#L22) and that one seems more correct (for example, it's used [in the types for utility methods](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5ca1e873b7d45542b10b27b065a79a851ceb728a/types/node/stream.d.ts#L293-L339)). Would you like to open a PR?

**Comment by rijkvanzanten** [comment]
Oh my bad, I just [quickly opened it on NPM](https://www.npmjs.com/package/stream), totally forgetting that `stream` is one of Node's core packages too 🙂 

I'll open a PR 👍
