### ISSUE TITLE
How to get registered drivers

### ISSUE THREAD

**Issue by rijkvanzanten** [Slynova-Org/flydrive#146]
I have a specific need where I need to check if a given driver is already registered in the StorageManager. Internally, Flydrive uses `this._drivers` as a private Map:

https://github.com/Slynova-Org/flydrive/blob/8e04e00b1e8433713acfbaac1beb8fbb37ddf9e5/packages/flydrive/src/StorageManager.ts#L34-L37

Would you accept a PR for a "get drivers" or public getter `drivers` to retrieve the previously registered drivers?

**Comment by RomainLanz** [comment]
Hey @rijkvanzanten! 👋 

Good idea! Would definitively accept a PR for that!

**Comment by rijkvanzanten** [comment]
@RomainLanz Do you have any preferences in terms of an API for this?

We could go with a `.getDrivers()`, or with a getter `.drivers`, or we could even "just" un-private the current `private _drivers` 🙂

**Comment by RomainLanz** [comment]
I believe `getDrivers()` is a good name.
