### ISSUE TITLE
Set subfolder as bucket root

### ISSUE THREAD

**Issue by hani-borsen** [Slynova-Org/flydrive#162]
Hi I have a Directus site and it uses flydrive for s3 file storage.
But I would like to use MyBucket/MySubFolder as the root of the filesystem.
Is the any way to configure this?

Right now Flydrive complaints about forward slashes if I change the bucket name from 'MyBucket' to 'MyBucket/MySubFolder' :)

**Comment by RomainLanz** [comment]
Hey @hani-borsen! 👋 

It seems that they are not using Flydrive, but their own fork.
I'd recommend that you open an issue in their repository.
