### ISSUE TITLE
S3 flatlist Delimiter

### ISSUE THREAD

**Issue by ManUtopiK** [Slynova-Org/flydrive#164]
We can list only directories with `Delimiter: '/'`. It could be useful to add this parameter also with `prefix`.

**Comment by damooo** [comment]
This seems essential for able to have sufficient abstraction layer for many use cases. As listing files in a directory without recursion is essential concept in many applications.
For example this is one such case https://github.com/solid/community-server/issues/963

**Comment by woutermont** [comment]
Has this been implemented, or was this closed for other reasons?
