### ISSUE TITLE
Is it still active?

### ISSUE THREAD

**Issue by blacksmoke26** [Slynova-Org/flydrive#71]
I am planning about using this in real project. Is it enough stable to use in production environment? Is development still active?

Thanks!

**Comment by RomainLanz** [comment]
Hey @blacksmoke26! 👋 

Yes, it is!
I haven't work on it for some time.
I have planned to do a rewrite in TS + adding some driver and merging all PRs but I haven't got the time to do so.

The actual code is still production ready and currently in used in many applications. 👌

**Comment by blacksmoke26** [comment]
Already using it :100:
