### ISSUE TITLE
[FEATURE REQUEST] Remove folder

### ISSUE THREAD

**Issue by annymosse** [Slynova-Org/flydrive#76]
this lib is great but still missing few of features such as remove folder, get files list inside a folder compress folder inside a [zip|tar|gz|7z|...]
good luck with your job and activities @RomainLanz

**Comment by RomainLanz** [comment]
Hey @annymosse! 👋 

This is out-of-scope of this package.
Feel free to use the `driver()` method in the next release to have access to the real driver behind our abstraction to do what you wanna do.

**Comment by annymosse** [comment]
> Hey @annymosse! 
> 
> This is out-of-scope of this package.
> Feel free to use the `driver()` method in the next release to have access to the real driver behind our abstraction to do what you wanna do.

im using adonis and using driver() but cant get files inside a folder or remove a folder or compress a folder,i solved these features using glob lib and others libs,thanks

**Comment by Nightbr** [comment]
Hey, really interested in this feature, @annymosse could you share your solution? 
Try to remove a folder with all its content but in an optimized way (not have to recursively delete all files).
Thanks :pray:

**Comment by annymosse** [comment]
> Hey, really interested in this feature, @annymosse could you share your solution?

as i had mentioned above i made (before longtime ago since 2019) a mixed solution with other libs such as [glob](https://www.npmjs.com/package/glob) for listing my files in array to do my own stuffs before delete these files **recursively** & [rimraf](https://www.npmjs.com/package/rimraf).

> Try to remove a folder with all its content but in an optimized way (not have to recursively delete all files).

As current of time i don't think there's a solution to remove folders with their contents without a recursive method (at least in *Unix OS).

There's ability to fix that old solution and provide a modern feature inside the kernels of these OS , since there's a new languages are planing to replace these old hard languages such as c & c++ with modern syntax and ability to reuse code/libs such as [Zig lang](https://github.com/ziglang/zig), [Rust lang](https://github.com/rust-lang/rust) and [V lang](https://github.com/vlang/v) even there's new OS made by rust and v.
Sorry for my delay to reply @Nightbr , and thanks for your interests.

**Comment by Nightbr** [comment]
For S3 driver, I use this method: https://github.com/bingtimren/s3-commons/blob/master/src/lib/deleteRecursive.ts
And usage is:

```
    const driver: S3 = this.myDisk.driver();
    const count = await deleteRecursive(driver, this.bucket, id + '/');
    return count;
```

It will optimize the Bulk delete using `deleteObjects`.

**Comment by annymosse** [comment]
@Nightbr as you can see at the function definition https://github.com/bingtimren/s3-commons/blob/878f0c8c7fae98c5d4b7036f21f549fc902c490d/src/lib/deleteRecursive.ts#L7 even S3 (which use Amazon Linux) there's no modified Linux kernel which let it stuck with recursive method too,  however because there's a key value feature (as i know it use hyper-storage for indexing and versioning history data) which is used to index the files and eliminate the need to recursively listing all sub-tree files/folders structures, @Nightbr ,if there's no plan to add remove folders without recursive method into the kernels i think your idea it's the best solution, adding a cache layer such as `Redis` to keep the structures up-to-date always and remove the folders using that cache without reading the trees each time.
