### ISSUE TITLE
[ftp driver] Drive.put()  does not works for nested folder

### ISSUE THREAD

**Issue by joy2g** [Slynova-Org/flydrive#90]
With ftp driver I can only use put method for the file without any parent folder:

+ For example:
Drive.put('test.txt') -> works
Drive.put('myfolder/test.txt') -> does not works

Any solution for this?
Appreciate your help

**Comment by molobala** [comment]
Can you share the error you get?

**Comment by joy2g** [comment]
Thanks for your reply:

This is what i get from the console: (I'm using Adonis)

await Drive.put("parent/child/test.txt", "Hello world")

warning:
  WARNING: Adonis has detected an unhandled promise rejection, which may
  cause undesired behavior in production.
  To stop this warning, use catch() on promises or wrap await
  calls inside try/catch.

{ Error: read ECONNRESET
    at exports._errnoException (util.js:1024:11)
    at TCP.onread (net.js:610:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }

This code will works just fine:
await Drive.put("test.txt", "Hello world")

**Comment by RomainLanz** [comment]
Hey ! 👋 

We are going to remove FTP driver in the next big release, therefore, I'm not going to fix this issue.
Feel free to create your own FTP driver and extends Flydrive with it.
